const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
async function load(){const p=new URL('../src/auto-reader.js',`file://${__filename}`);assert.ok(fs.existsSync(p),'automatic TTS controller missing');return import(p);}
function engine(){const said=[],jobs=[],states=[],moves=[];let cancels=0;const synth={getVoices:()=>[{lang:'ko-KR',localService:true}],speak:u=>said.push(u),cancel:()=>{cancels++}};class U{constructor(t){this.text=t;}}
return {said,jobs,states,moves,synth,Utterance:U,readout:id=>['사건 '+id],next:id=>id<2?id+1:null,onNavigate:id=>moves.push(id),onState:s=>states.push(s),schedule:fn=>{jobs.push(fn);return fn;},unschedule:fn=>{const n=jobs.indexOf(fn);if(n>=0)jobs.splice(n,1);},get cancels(){return cancels;}};}
test('TTS does not speak until an explicit start, then advances and stops at end',async()=>{const m=await load(),e=engine(),r=m.createAutoReader(e);assert.equal(e.said.length,0);r.start(1);assert.equal(e.said[0].text,'사건 1');e.said[0].onend();assert.equal(e.moves.length,0);e.jobs.shift()();assert.deepEqual(e.moves,[2]);assert.equal(e.said[1].text,'사건 2');e.said[1].onend();e.jobs.shift()();assert.equal(r.playing,false);assert.equal(e.said.length,2);});
test('cancel invalidates stale onend and queued next-event callbacks',async()=>{const m=await load(),e=engine(),r=m.createAutoReader(e);r.start(1);const old=e.said[0];old.onend();const delayed=e.jobs[0];r.stop();old.onend();delayed();assert.equal(e.moves.length,0);assert.equal(r.playing,false);assert.equal(e.jobs.length,0);});
test('switching readouts cannot replay a cancelled utterance',async()=>{const m=await load(),e=engine(),r=m.createAutoReader(e);r.start(1);const stale=e.said[0];r.start(2);stale.onend();assert.equal(e.jobs.length,0);assert.equal(e.said.length,2);assert.equal(e.said[1].text,'사건 2');});
test('unavailable Korean voice and speech failures do not advance events',async()=>{const m=await load(),e=engine();e.synth.getVoices=()=>[];const r=m.createAutoReader(e);assert.equal(r.start(1),false);assert.equal(e.said.length,0);assert.ok(e.states.at(-1).message.includes('한국어'));e.synth.getVoices=()=>[{lang:'ko-KR'}];r.start(1);e.said[0].onerror({error:'not-allowed'});assert.equal(r.playing,false);assert.equal(e.moves.length,0);});
test('long readouts speak in ordered chunks before advancing',async()=>{const m=await load(),e=engine();e.readout=id=>['첫째','둘째'];const r=m.createAutoReader(e);r.start(1);e.said[0].onend();assert.equal(e.said[1].text,'둘째');assert.equal(e.moves.length,0);r.stop();});
