const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const modulePath=new URL('../src/series-core.js',`file://${__filename}`);
async function load(){assert.ok(fs.existsSync(modulePath),'series core is implemented');return import(modulePath);}
const events=[{id:1,timeline_date:'1805',date_precision:'year'},{id:2,timeline_date:'1700-04',date_precision:'month'},{id:3,timeline_date:'1805-02-01'},{id:4,timeline_date:'1600/1610'}];
test('series members are unique, available IDs only and chronological without changing dates',async()=>{const m=await load();const orig=JSON.stringify(events);assert.deepEqual(m.orderedMembers([3,1,2,2,999],new Map(events.map(x=>[x.id,x]))),[2,1,3]);assert.equal(JSON.stringify(events),orig);});
test('concept combinations support union/intersection without interpreting causal relationships',async()=>{const m=await load(),cs=[{id:1,events:[1,2]},{id:2,events:[2,3]}];assert.deepEqual(m.combineConcepts(cs,[1,2],'any'),[1,2,3]);assert.deepEqual(m.combineConcepts(cs,[1,2],'all'),[2]);assert.deepEqual(m.combineConcepts(cs,[999],'any'),[]);});
test('previous and next stop at series boundaries and outsider never silently skips first',async()=>{const m=await load();assert.deepEqual(m.neighbours([2,1,3],1),{index:1,previous:2,next:3});assert.deepEqual(m.neighbours([2,1,3],999),{index:-1,previous:null,next:2});assert.equal(m.neighbours([2,1,3],3).next,null);});
test('Escape priority: dialog then settings then suggestions then detail; repeat ignored',async()=>{const m=await load();assert.equal(m.escapeAction({dialog:true,detail:true}),'dialog');assert.equal(m.escapeAction({settings:true,detail:true}),'settings');assert.equal(m.escapeAction({search:true,detail:true}),'search');assert.equal(m.escapeAction({detail:true}),'timeline');assert.equal(m.escapeAction({detail:true,repeat:true}),'none');});
test('catalogue rejects duplicate series IDs, malformed members and wrong schema',async()=>{const m=await load();assert.throws(()=>m.validateCatalogue({schema:0,series:[],concepts:[]}));assert.throws(()=>m.validateCatalogue({schema:1,series:[{id:'a',events:[1]},{id:'a',events:[2]}],concepts:[]}));assert.throws(()=>m.validateCatalogue({schema:1,series:[],concepts:[{id:1,name:'a',type:'topic',events:[true]}]}));});
