import {createDetailSeriesUI} from './detail-series.js';
import config from './series-config.js';
import {orderedMembers,combineConcepts,neighbours,validateCatalogue,groupSeriesChoices} from './series-core.js';
const KEY='stw-series-state-v1',CUSTOM='stw-custom-series-v1';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
const button=(label,fn,cls='')=>{const e=text('button',label,cls);e.type='button';e.addEventListener('click',fn);return e;};
export function createSeriesUI({getEvents,onFilter,onNavigate,onDetail,getReadout}){
 const dialog=document.getElementById('seriesDialog'),open=document.getElementById('seriesOpen'),query=document.getElementById('seriesSearch'),results=document.getElementById('seriesResults'),bar=document.getElementById('seriesBar'),detail=document.getElementById('seriesDetailNav');
 let catalog=null,pending=null,active=null,members=[],memberSet=new Set(),context=false,current=null,picked=new Set(),custom=[],limit=80,mode='browse';
 let saved=null;try{saved=JSON.parse(localStorage.getItem(KEY)||'null');custom=JSON.parse(localStorage.getItem(CUSTOM)||'[]');if(!Array.isArray(custom))custom=[];custom=custom.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&Array.isArray(x.concept_ids)).slice(0,50);}catch{custom=[];}
 const detailControls=createDetailSeriesUI({loadCatalogue:load,getEvents,getCustomSeries:()=>custom,onDetail,getReadout});
 const byId=()=>new Map(getEvents().map(x=>[x.id,x]));
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({id:active?.id||null,context}));localStorage.setItem(CUSTOM,JSON.stringify(custom));}catch{document.getElementById('seriesNotice').textContent='브라우저 저장이 차단되어 이번 방문에서만 유지됩니다.';}};
 async function load(){if(catalog)return catalog;if(pending)return pending;
  pending=(async()=>{const response=await fetch(new URL(config.file,document.baseURI),{signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('시리즈 자료를 읽지 못했습니다.');const bytes=await response.arrayBuffer();if(bytes.byteLength>20*1024*1024)throw new Error('시리즈 자료가 너무 큽니다.');const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==config.sha256)throw new Error('시리즈 자료 검증에 실패했습니다. 새로고침해 주세요.');const encoded=new TextDecoder().decode(bytes).trim(),raw=Uint8Array.from(atob(encoded),x=>x.charCodeAt(0));const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'));catalog=validateCatalogue(JSON.parse(await new Response(stream).text()));return catalog;})().finally(()=>pending=null);return pending;
 }
 function selection(s,map=byId()){const ids=s.concept_ids?combineConcepts(catalog.concepts,s.concept_ids,s.match):s.events;return orderedMembers(ids,map);}
 function notify(){onFilter({active,ids:memberSet,context});renderBar();}
 function select(s,{restore=false}={}){active=s;members=selection(s);memberSet=new Set(members);current=null;save();notify();if(!restore){dialog.close();if(members.length)onNavigate(members[0]);} }
 function clear(){detailControls.clear();active=null;members=[];memberSet=new Set();current=null;save();notify();}
 function step(direction,detailMode){const n=neighbours(members,current),id=direction<0?n.previous:n.next;if(id!=null){current=id;if(detailMode)onDetail(id);else onNavigate(id);renderBar();}}
 function renderBar(){bar.replaceChildren();bar.hidden=!active;open.classList.toggle('selected',!!active);open.textContent=active?'시리즈 ✓':'시리즈';if(!active)return;
  const title=button(active.title,()=>show('members'),'series-bar-title');title.title='시리즈 사건 목록 열기';
  const n=neighbours(members,current),counter=text('span',`${n.index>=0?n.index+1:0} / ${members.length.toLocaleString()}건`,'series-count');
  const prev=button('이전',()=>step(-1,false),'series-step'),next=button('다음',()=>step(1,false),'series-step');prev.disabled=n.previous==null;next.disabled=n.next==null;
  const toggle=button(context?'세계 함께 보기':'관련 사건만',()=>{context=!context;save();notify();},'series-context');toggle.setAttribute('aria-pressed',String(context));toggle.title='관련 사건만 표시하거나 같은 시기의 세계 사건을 함께 봅니다.';
  const close=button('해제',clear,'series-clear');bar.append(title,counter,prev,next,toggle,close);
 }

 function renderBuilder(){const box=document.getElementById('seriesBuilder');box.hidden=picked.size===0;document.getElementById('seriesPicked').textContent=[...picked].map(id=>catalog.concepts.find(x=>x.id===id)?.name||'').join(' · ');}
 function makeCustom(){const ids=[...picked],match=document.getElementById('seriesMatch').value,title=document.getElementById('seriesName').value.trim()||ids.map(id=>catalog.concepts.find(x=>x.id===id)?.name).join(' + ');if(!ids.length)return;
  const s={id:'local-'+Date.now().toString(36),title:title.slice(0,100),concept_ids:ids,match,kind:'local',description:'이 브라우저에 저장한 개념 조합'};if(!selection(s).length){document.getElementById('seriesNotice').textContent='이 조합에 해당하는 사건이 없습니다. ‘하나 이상’을 선택하거나 개념을 바꿔 주세요.';return;}custom.unshift(s);custom=custom.slice(0,50);select(s);picked.clear();renderBuilder();document.getElementById('seriesName').value='';}
 function card(s,map){const ids=selection(s,map),node=document.createElement('div');node.className='series-choice';const choose=button('',()=>select(s),'series-choice-main');choose.append(text('strong',s.title),text('small',`${ids.length.toLocaleString()}건 · ${s.kind==='local'?'내 브라우저 저장':s.kind==='entity'?`${s.entity_label||'대상'} 기록`:'개념 기반 자동 모음'}`),text('span',s.description||''));node.append(choose);if(s.kind==='local')node.append(button('삭제',()=>{custom=custom.filter(x=>x.id!==s.id);if(active?.id===s.id)clear();save();renderResults();},'series-delete'));return node;}
 function renderResults(){if(!catalog)return;results.replaceChildren();const q=query.value.trim().normalize('NFKC').toLowerCase();document.getElementById('seriesNotice').textContent='기존 자료의 개념 연결로 모았습니다. 완성된 인과관계·서사로 검증한 시리즈는 아닙니다.';
  if(mode==='members'&&active){const map=byId(),filtered=members.filter(id=>{const e=map.get(id);return !q||[e.title,e.date,e.country,e.locality].join(' ').toLowerCase().includes(q);});results.append(text('h3',`${active.title} · ${filtered.length.toLocaleString()}건`));for(const id of filtered.slice(0,limit)){const e=map.get(id),b=button('',()=>{dialog.close();current=id;onNavigate(id);renderBar();},'series-event');b.append(text('small',e.date_label||e.date),text('strong',e.title),text('span',e.locality||e.country||'지역 미상'));results.append(b);}if(filtered.length>limit)results.append(button('더 보기',()=>{limit+=80;renderResults();},'series-more'));if(!filtered.length)results.append(text('p','일치하는 사건이 없습니다.'));return;}
  const ss=[...custom,...catalog.series].filter(s=>!q||[s.title,s.description].join(' ').toLowerCase().includes(q));if(ss.length){const map=byId();for(const group of groupSeriesChoices(ss)){results.append(text('h3',group.title,'series-category-title'));for(const s of group.rows)results.append(card(s,map));}}
  const cs=catalog.concepts.filter(c=>!q?(c.type==='topic'&&c.events.length>=20):c.name.normalize('NFKC').toLowerCase().includes(q)).sort((a,b)=>b.events.length-a.events.length||a.name.localeCompare(b.name));
  results.append(text('h3',q?`개념 검색 · ${cs.length.toLocaleString()}개`:'개념을 골라 시리즈 만들기'));
  const typeName={topic:'주제',place:'장소',polity:'정치체',person:'인물',technology:'기술'};
  for(const c of cs.slice(0,limit)){const row=document.createElement('div');row.className='concept-choice';const check=document.createElement('input');check.type='checkbox';check.checked=picked.has(c.id);check.setAttribute('aria-label',c.name+' 조합에 추가');check.addEventListener('change',()=>{if(check.checked&&picked.size>=8){check.checked=false;document.getElementById('seriesNotice').textContent='한 번에 개념 8개까지 조합할 수 있습니다.';return;}if(check.checked)picked.add(c.id);else picked.delete(c.id);renderBuilder();});const go=button('',()=>select({id:'concept-'+c.id,title:c.name,concept_ids:[c.id],match:'any',kind:'concept'}));go.append(text('strong',c.name),text('small',`${typeName[c.type]||c.type} · ${c.events.length.toLocaleString()}건`));row.append(check,go);results.append(row);}
  if(cs.length>limit)results.append(button('더 보기',()=>{limit+=80;renderResults();},'series-more'));if(!ss.length&&!cs.length)results.append(text('p','일치하는 시리즈·개념이 없습니다.'));
 }
 async function show(next='browse'){detailControls.stopSpeech();mode=next;limit=80;query.value='';dialog.showModal();query.focus();results.replaceChildren(text('p','시리즈 자료를 읽는 중입니다…'));try{await load();renderResults();renderBuilder();}catch(e){results.replaceChildren(text('p',e.message),button('다시 읽기',()=>{dialog.close();show(next);}));}}
 open.addEventListener('click',()=>show());document.getElementById('seriesClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 let timer;query.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{limit=80;renderResults();},100);});document.getElementById('seriesBrowse').addEventListener('click',()=>{mode='browse';query.value='';limit=80;renderResults();});document.getElementById('seriesMembers').addEventListener('click',()=>{mode='members';query.value='';limit=80;renderResults();});document.getElementById('seriesSave').addEventListener('click',makeCustom);document.getElementById('seriesResetPicked').addEventListener('click',()=>{picked.clear();renderBuilder();renderResults();});
 document.getElementById('seriesExport').addEventListener('click',()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({schema:1,custom},null,2)],{type:'application/json'}));a.href=url;a.download='SameTimeWorld_my_series.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return {showDetail(id,options){return detailControls.setEvent(id,options);},leaveDetail(){detailControls.leave();},stopSpeech(){detailControls.stopSpeech();},setCurrent(id){current=id;renderBar();},clear,async restore(){if(!saved?.id)return;try{await load();context=!!saved.context;const s=[...custom,...catalog.series].find(x=>x.id===saved.id)||(/^concept-\d+$/.test(saved.id)?catalog.concepts.filter(x=>x.id===Number(saved.id.slice(8))).map(x=>({id:saved.id,title:x.name,concept_ids:[x.id],match:'any'}))[0]:null);if(s){select(s,{restore:true});if(members.length)onNavigate(members[0]);}}catch{open.title='저장한 시리즈를 복원하지 못했습니다. 클릭하여 다시 시도하세요.';}},get selection(){return {active,ids:memberSet,context};}};
}
